import requests
token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6InNUWGI5bl9pbVEtdDZiNV92OWNxNnk4Ni0ySVVyWUdURE85RnIwNHNCTjgiLCJhbGciOiJSUzI1NiIsIng1dCI6ImtXYmthYTZxczh3c1RuQndpaU5ZT2hIYm5BdyIsImtpZCI6ImtXYmthYTZxczh3c1RuQndpaU5ZT2hIYm5BdyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC80Njg1ZDE4OS1mOWRkLTQ0ZTUtYjY1NC1kNGEzYmM2ZjkxOWIvIiwiaWF0IjoxNzA4MjgzMDU5LCJuYmYiOjE3MDgyODMwNTksImV4cCI6MTcwODI4Njk1OSwiYWlvIjoiRTJOZ1lHQ1VWWlRlMW52dW40K2kvbFUxbDF4NUFBPT0iLCJhcHBfZGlzcGxheW5hbWUiOiJ0ZWFtcy1hZ2VudCIsImFwcGlkIjoiMTZjYmUyNjYtOGQ0OC00MDY5LWE3MDQtOWJkOWQ3ZjM3OWJkIiwiYXBwaWRhY3IiOiIxIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNDY4NWQxODktZjlkZC00NGU1LWI2NTQtZDRhM2JjNmY5MTliLyIsImlkdHlwIjoiYXBwIiwib2lkIjoiNjQ3ZTgyY2UtYzY1Yi00NWZjLTgxZmItNmFlZjc1YjVmOTcyIiwicmgiOiIwLkFhZ0FpZEdGUnQzNTVVUzJWTlNqdkctUm13TUFBQUFBQUFBQXdBQUFBQUFBQUFEekFBQS4iLCJyb2xlcyI6WyJPbmxpbmVNZWV0aW5ncy5SZWFkV3JpdGUuQWxsIiwiVXNlci5SZWFkV3JpdGUuQWxsIiwiT25saW5lTWVldGluZ0FydGlmYWN0LlJlYWQuQWxsIiwiT25saW5lTWVldGluZ1JlY29yZGluZy5SZWFkLkFsbCIsIk9ubGluZU1lZXRpbmdUcmFuc2NyaXB0LlJlYWQuQWxsIl0sInN1YiI6IjY0N2U4MmNlLWM2NWItNDVmYy04MWZiLTZhZWY3NWI1Zjk3MiIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJOQSIsInRpZCI6IjQ2ODVkMTg5LWY5ZGQtNDRlNS1iNjU0LWQ0YTNiYzZmOTE5YiIsInV0aSI6ImZsZkVfTFhFblVHS1JKbmlsWEVTQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjA5OTdhMWQwLTBkMWQtNGFjYi1iNDA4LWQ1Y2E3MzEyMWU5MCJdLCJ4bXNfdGNkdCI6MTcwODE5NjkxNH0.Cc9KFkykn_c64MsFjn9QCyfXuGFBrXZZAuPqzrWCodHRIuKDLIBOpM1HFWADfndwBhWs5FX8-ljl9tAFp0M6dNJxO9Z2x1NA9zAR9wKVr1Jrm-aT3vqYguqEt__KgingndBioTKppkBj1iqFjBnuAbWAClv3vS1isip7IV2ECf-oqTqsMyZjT37tySvpbOh37_G8cbx4LtDJoSzeeRT7kXhIeVQcfRv4rejIeTKNxA8HpDZ32A2vKALSA5PGcGUHqbr36rM08KNaMahQWWnLJoX7GKoaodeVJfvs1VlArr1j3qffI_g1yuNxOLynf6_OTUVhQC0vn2nyrOin9cwZhg"
# Microsoft Graph URL and headers for the user query
graph_url = 'https://graph.microsoft.com/v1.0/users'
headers = {'Authorization': f'Bearer {token}'}
params = {'$filter': f"userPrincipalName eq 'shreyas.kar_gmail.com#EXT#@shreyaskargmail.onmicrosoft.com'"}

# Making the request to get user information
user_r = requests.get(graph_url, headers=headers, params=params)
user_data = user_r.json()
# Extracting and printing the user ID
if user_data.get('value'):
    user_id = user_data['value'][0]['id']
    print(user_id)
else:
    print('User not found')
